# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

libgdalcubes_is_null <- function(pointer) {
    .Call('_gdalcubes_libgdalcubes_is_null', PACKAGE = 'gdalcubes', pointer)
}

libgdalcubes_version <- function() {
    .Call('_gdalcubes_libgdalcubes_version', PACKAGE = 'gdalcubes')
}

libgdalcubes_init <- function() {
    invisible(.Call('_gdalcubes_libgdalcubes_init', PACKAGE = 'gdalcubes'))
}

libgdalcubes_cleanup <- function() {
    invisible(.Call('_gdalcubes_libgdalcubes_cleanup', PACKAGE = 'gdalcubes'))
}

libgdalcubes_cube_info <- function(pin) {
    .Call('_gdalcubes_libgdalcubes_cube_info', PACKAGE = 'gdalcubes', pin)
}

libgdalcubes_open_image_collection <- function(filename) {
    .Call('_gdalcubes_libgdalcubes_open_image_collection', PACKAGE = 'gdalcubes', filename)
}

libgdalcubes_create_image_collection_cube <- function(filename, v = NULL) {
    .Call('_gdalcubes_libgdalcubes_create_image_collection_cube', PACKAGE = 'gdalcubes', filename, v)
}

libgdalcubes_create_reduce_cube <- function(pin, reducer) {
    .Call('_gdalcubes_libgdalcubes_create_reduce_cube', PACKAGE = 'gdalcubes', pin, reducer)
}

libgdalcubes_eval_reduce_cube <- function(pin, outfile, of) {
    invisible(.Call('_gdalcubes_libgdalcubes_eval_reduce_cube', PACKAGE = 'gdalcubes', pin, outfile, of))
}

libgdalcubes_create_stream_cube <- function(pin, cmd, chunk_size) {
    .Call('_gdalcubes_libgdalcubes_create_stream_cube', PACKAGE = 'gdalcubes', pin, cmd, chunk_size)
}

libgdalcubes_set_threads <- function(n) {
    invisible(.Call('_gdalcubes_libgdalcubes_set_threads', PACKAGE = 'gdalcubes', n))
}

